apiVersion: v1
kind: Service
metadata:
  name: powerlifting-app-backend
  labels:
    app: powerlifting-app-backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3005"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3005
      targetPort: 3005
      protocol: TCP
  selector:
    app: powerlifting-app-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerlifting-app-backend
  labels:
    app: powerlifting-app-backend
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: powerlifting-app-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: powerlifting-app-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3005"
        prometheus.io/path: "/metrics"
    spec:
      automountServiceAccountToken: true
      imagePullSecrets:
        - name: ecr-registry
      volumes:
        - name: aws-credentials
          hostPath:
            path: /root/.aws
            type: Directory
      containers:
        - name: backend
          image: 429310424269.dkr.ecr.ca-central-1.amazonaws.com/if-powerlifting-app-backend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3005
              protocol: TCP
          envFrom:
            - configMapRef:
                name: powerlifting-app-config
                optional: false
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: aws-credentials
              mountPath: /root/.aws
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: 3005
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3005
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
