apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: 429310424269.dkr.ecr.ca-central-1.amazonaws.com/if-powerlifting-app-backend
    newName: 429310424269.dkr.ecr.ca-central-1.amazonaws.com/if-powerlifting-app-backend
    newTag: latest
  - name: 429310424269.dkr.ecr.ca-central-1.amazonaws.com/if-powerlifting-app-frontend
    newName: 429310424269.dkr.ecr.ca-central-1.amazonaws.com/if-powerlifting-app-frontend
    newTag: latest

resources:
  - backend.yaml
  - frontend.yaml
