import os

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
LLM_BASE_URL = os.getenv("LLM_BASE_URL", "https://openrouter.ai/api/v1")
ANALYSIS_MODEL = os.getenv("ANALYSIS_MODEL", "anthropic/claude-sonnet-4.6")
ESTIMATE_MODEL = os.getenv("ESTIMATE_MODEL", ANALYSIS_MODEL)
ESTIMATE_MODEL_REASONING_EFFORT = os.getenv("ESTIMATE_MODEL_REASONING_EFFORT", "xhigh")
ESTIMATE_MODEL_VERBOSITY = os.getenv("ESTIMATE_MODEL_VERBOSITY", "max")
GLOSSARY_TEXT_MODEL = os.getenv("GLOSSARY_TEXT_MODEL", "google/gemini-3.1-flash-lite")
IMPORT_FAST_MODEL = os.getenv("IMPORT_FAST_MODEL", "anthropic/claude-haiku-4.5")
ANALYSIS_MODEL_THINKING_BUDGET = int(os.getenv("ANALYSIS_MODEL_THINKING_BUDGET", "16000"))
HEALTH_HELPER_MODEL = os.getenv("HEALTH_HELPER_MODEL", "openai/gpt-5.4-mini")
HEALTH_HELPER_MODEL_REASONING_EFFORT = os.getenv("HEALTH_HELPER_MODEL_REASONING_EFFORT", "low")
HEALTH_HELPER_MODEL_VERBOSITY = os.getenv("HEALTH_HELPER_MODEL_VERBOSITY", "low")
